-- Modelo relacional equivalente ao gerado pelo JPA.
-- O sistema cria e atualiza as tabelas automaticamente no banco H2.

CREATE TABLE coordenadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha_hash VARCHAR(500) NOT NULL
);

CREATE TABLE voluntarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    matricula VARCHAR(30) NOT NULL UNIQUE,
    curso VARCHAR(120) NOT NULL,
    telefone VARCHAR(30),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    senha_hash VARCHAR(500) NOT NULL
);

CREATE TABLE atividades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    descricao VARCHAR(1000) NOT NULL,
    data DATE NOT NULL,
    local VARCHAR(150) NOT NULL,
    horas_previstas DECIMAL(6,2) NOT NULL,
    status VARCHAR(30) NOT NULL
);

CREATE TABLE participacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voluntario_id BIGINT NOT NULL,
    atividade_id BIGINT NOT NULL,
    horas_realizadas DECIMAL(6,2) NOT NULL,
    presente BOOLEAN NOT NULL,
    observacao VARCHAR(500),
    CONSTRAINT uk_participacao UNIQUE (voluntario_id, atividade_id),
    CONSTRAINT fk_participacao_voluntario FOREIGN KEY (voluntario_id)
        REFERENCES voluntarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_participacao_atividade FOREIGN KEY (atividade_id)
        REFERENCES atividades(id) ON DELETE CASCADE
);
